version: "3.3"

services:
  jenkins:
    container_name: demo_jenkins
    platform: linux/x86_64
    image: jenkinsci/blueocean
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_home:/var/jenkins_home
    networks:
      - jenkins-red

volumes:
  jenkins_home:
    driver: local

networks:
  jenkins-red:
    driver: bridge